#!/bin/sh

# configuration

user=yourusername
passwd=yourpasswd


# quelques fonctions

testPing () {
    title=$(wget -q --timeout 5 -O - perdu.com | grep title | sed "s#.*<title>\(.*\)</title>.*#\1#")
    [ "$title" = "Vous Etes Perdu ?" ]
}

extract () {
    echo $1 | sed "s/.*$2=\([^&]*\)\(&.*\|$\)/\1/"
}


# code principal

# testons la connexion
testPing
if [ $? -eq 0 ]; then
    echo "La connexion est déjà active."
    exit
fi

# si la connexion n'est pas active
echo "Connexion en cours…"


# on récupère l'url du portail
url=$(wget --max-redirect 0 -O - perdu.com 2>&1 | grep hotspot.wifi.sfr.fr | sed 's/.*\(https[^ ]*\).*/\1/')
if [ -z "$url" ]; then
    echo "Erreur lors de la récupération de l'url de la page de connexion." >&2
    echo "Etes vous connecté à un SFR WiFi ?" >&2
    exit 1
fi

# on complète le formulaire
for i in challenge mode channel uamip uamport mac; do
    eval $i=$(extract $url $i)
done

form="username=$user&&password=$passwd"
form+="&conditions=1&&save=0"
form+="&challenge=$challenge"
form+="&accessType=neuf"
form+="&lang=fr"
form+="&userurl=http%3a%2f%2fperdu.com%2f"
form+="&mode=$mode"
form+="&uamip=$uamip"
form+="&uamport=$uamport"
form+="&mac=$mac"

# on se connecte
tmp=$(mktemp /tmp/sfrconnectXXXX)
wget -q --post-data $form -O $tmp https://hotspot.wifi.sfr.fr/nb4_crypt.php 2>&1 > /dev/null

if [ $? -ne 0 ]; then
    echo "Erreur lors de l'envoie de vos identifiants." >&2
    exit 2
fi

#cat $tmp
urlConfirm=$(grep 'window.location' $tmp | sed 's#^.*\(http://[^ ]*\)";.*#\1#')
rm $tmp
wget -q $urlConfirm -O /dev/null 2>&1 > /dev/null

if [ $? -ne 0 ]; then
    echo "Erreur lors de la connexion. Vérifiez que vos identifiants sont correctes." >&2
    exit 2
fi

# on vérifie la connexion
testPing
if [ $? -eq 0 ]; then
    echo 'Connexion effectuée.'
else
    echo 'Erreur.' >&2
    exit 2
fi
